name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Set timestamp
      run: |
        echo "TIMESTAMP=v$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TIMESTAMP }}
        files: |
          app/build/outputs/apk/debug/app-debug.apk
      
