name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Generate Keystore file from Github Secrets
        run: |
          echo "${{ secrets.APP_KEYSTORE_BASE64 }}" > ./keystore.b64
          base64 -d -i ./keystore.b64 > ./${{ secrets.KEYFILE }}
          cp ./${{ secrets.KEYFILE }} ./app/${{ secrets.KEYFILE }}

      - name: Build signed APK
        run: |
          bash ./gradlew assembleRelease \
            -P android.injected.signing.store.file=${{ secrets.KEYFILE }} \
            -P android.injected.signing.store.password=${{ secrets.STORE_PASSWORD }} \
            -P android.injected.signing.key.alias=${{ secrets.KEY_ALIAS }}  \
            -P android.injected.signing.key.password=${{ secrets.KEY_PASSWORD }} \
            --stacktrace

      - name: Set timestamp
        run: |
          echo "TIMESTAMP=v$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TIMESTAMP }}
          files: |
            app/build/outputs/apk/release/Pokedex.apk
